### ISSUE TITLE
Crashes when using require() due to syntax error

### ISSUE THREAD

**Issue by Bossehasse** [azain/electron-window-manager#22]
Sorry, couldn't come up with a better title.

Anyway, it crashes when I use require() in my electron.js file and gives me the following syntax errors:

```
/Users/Bossehasse/projects/vagranti_testing/node_modules/electron-window-manager/index.js:1096
                      'emit': function(event, data, target){
                      ^^^^^^
          SyntaxError: Unexpected string
              at Object.exports.runInThisContext (vm.js:76:16)
              at Module._compile (module.js:528:28)
              at Object.Module._extensions..js (module.js:565:10)
              at Module.load (module.js:473:32)
              at tryModuleLoad (module.js:432:12)
              at Function.Module._load (module.js:424:3)
              at Module.require (module.js:483:17)
              at require (internal/module.js:20:19)
              at Object.<anonymous> (/Users/Bossehasse/projects/vagranti_testing/app/electron.js:9:23)
              at Module._compile (module.js:556:32)
```

```
Uncaught Exception:
TypeError: Cannot read property 'bridge' of undefined
    at Object.<anonymous> (/Users/Bossehasse/projects/vagranti_testing/node_modules/electron-window-manager/index.js:1077:41)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Bossehasse/projects/vagranti_testing/app/electron.js:9:23)
    at Module._compile (module.js:556:32)

```

```javascript
    // index.js
        'bridge': {
            'on': function(event, callback){
                let id =  windowManager.eventEmitter.listenerCount(event);

                windowManager.eventEmitter.addListener(event, function(event){
                    callback.call(null, event.data, event.target, event.emittedBy);
                });

                return windowManager.eventEmitter.listeners(event)[id];
            },

            'addListener': windowManager.bridge.on, // <---- Properties can't be added like this, it says that windowManager is undefined.

            'removeListener': function(event, handler) {
                windowManager.eventEmitter.removeListener(event, handler);
            } // <----- a "," is missing.

            'emit': function(event, data, target){
                windowManager.eventEmitter.emit(event, {
                    'emittedBy': windowManager.getCurrent().name,
                    'target': target,
                    'data': data
                });
            }
        }
```

I'm using version 1.0.2 which is the latest, I believe?

**Comment by azain** [comment]
Yeah sorry, my bad. Try again now.

**Comment by Bossehasse** [comment]
Thanks, man! Everything seems to work!
