### ISSUE TITLE
Window.currentURL() does not work.

### ISSUE THREAD

**Issue by Bossehasse** [azain/electron-window-manager#23]
```
Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: this.content(...).getUrl is not a function
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: this.content(...).getUrl is not a function
    at callFunction (/Users/Bossehasse/projects/vagranti_testing/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:235:11)
    at EventEmitter.<anonymous> (/Users/Bossehasse/projects/vagranti_testing/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:342:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Users/Bossehasse/projects/vagranti_testing/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

The issue seems to be because of a misspelling:

```javascript
// index.js line 351
Window.prototype.currentURL = function(){
        return this.content().getUrl(); // <--- Should be getURL()
    };
```

**Comment by azain** [comment]
Yeah, Electron changed the method name earlier. Will fix it, thanks.

**Comment by azain** [comment]
Fixed.
