### ISSUE TITLE
Error when creating a window from rendered process

### ISSUE THREAD

**Issue by L3V147H4N** [azain/electron-window-manager#9]
```
Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cannot read property 'webContents' of null
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cannot read property 'webContents' of null
    at callFunction (D:\Reactron\node_modules\electron-prebuilt\dist\resources\electron.asar\browser\rpc-server.js:225:11)
    at EventEmitter.<anonymous> (D:\Reactron\node_modules\electron-prebuilt\dist\resources\electron.asar\browser\rpc-server.js:306:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (D:\Reactron\node_modules\electron-prebuilt\dist\resources\electron.asar\browser\api\web-contents.js:165:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

code:
```
var remote = require('electron').remote;
    console.log(remote);
    const {
      app
    } = remote.require('electron');
    var windowManager = remote.require('electron-window-manager');

    console.log('main window script');

    console.log('create');
    // Create a new window
    var win2 = windowManager.createNew('win2', 'Windows #2');
    win2.loadURL(app.getAppPath() + '\\out\\modal\\process-modal.html');
    win2.open();

```

**Comment by gschmottlach-xse** [comment]
I've had a similar problem in the past. It seems the 'remote' module is pretty picky when it comes to matching methods and signatures. What I found is that I **must** specify all the arguments (event the optional ones) in the createNew() method call. So in your case, it might become:

```
var win2 = windowManager.createNew('win2', 'Windows #2', null, false, {}, false);
```

Give that a try and see if it fixes your problem.

**Comment by shrimpwagon** [comment]
@L3V147H4N Did @gschmottlach-xse  fix your issue?

@azain Close if this is resolved please

**Comment by L3V147H4N** [comment]
sorry, I abstained from using this library, I will test it further more in the future

**Comment by loicboyeldieu** [comment]
Unfortunately, I gave a try to @gschmottlach-xse but did not work. Any other suggestions ?

**Comment by Zyles** [comment]
Does not work for me either.

```
Uncaught Error: Could not call remote function 'createNew'. Check that the function signature is correct. Underlying error: Cannot read property 'focus' of null
Error: Could not call remote function 'createNew'. Check that the function signature is correct. Underlying error: Cannot read property 'focus' of null
```
